name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    name: Test

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: 20

      - uses: astral-sh/setup-uv@v3
        with:
          version: ">=0.5.0"
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"

      - name: Install Node dependencies
        run: npm ci

      - run: npm run build
